AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaCodeBucket:
    Type: String
    Default: task-tracker-bucket-holly-1743805064  
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: hello-world.handler
      Role: !GetAtt MyLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: lambda-code.zip
      Runtime: nodejs18.x
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole